services:
  accounts-service:
    image: "bunshock/accounts:v1"
    container_name: "hipbank-accounts_ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - hipbank-network
  loans-service:
    image: "bunshock/loans:v1"
    container_name: "hipbank-loans_ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - hipbank-network
  cards-service:
    image: "bunshock/cards:v1"
    container_name: "hipbank-cards_ms"
    ports:
      - "8100:8100"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - hipbank-network
networks:
  hipbank-network:
    driver: "bridge"