services:

  rabbit:
    image: "rabbitmq:4-management"
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  accounts-service:
    image: "bunshock/accounts:v1"
    container_name: "hipbank-accounts_ms"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-profile-config

  loans-service:
    image: "bunshock/loans:v1"
    container_name: "hipbank-loans_ms"
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-profile-config

  cards-service:
    image: "bunshock/cards:v1"
    container_name: "hipbank-cards_ms"
    ports:
      - "8100:8100"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-profile-config

  configserver:
    image: "bunshock/configserver:v1"
    container_name: "hipbank-configserver_ms"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  hipbank-network:
    driver: "bridge"