build:
  version: "1.0.0-SNAPSHOT"

accounts:
  message: "Welcome to HipBank cards microservice"
  contactDetails:
    name: "Bunshock"
    email: "bunshock@me.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1345
